name: Api Pull Request

on:
    pull_request:
        types: [opened, reopened]

jobs:
    Check_App:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2

            - name: Generate Environment Variables
              uses: SpicyPizza/create-envfile@v1
              with:
                  envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  file_name: .env

            - name: Inject slug/short variables
              uses: rlespinasse/github-slug-action@v3.x

            - name: Install NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Cache node_modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}

            - name: Install Packages
              run: yarn install

            - name: ESLint
              run: yarn lint

            - name: Unit Test
              run: yarn test:cov

            - name: E2E Test
              run: yarn test:e2e

            - name: Build
              run: yarn build

            - name: Slack Notification on SUCCESS
              if: ${{ success() }}
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                  text: '*<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|MySpot API  Pre-Check Succeed::${{ env.GITHUB_REF_SLUG }}>*'
                  attachments: |
                      [
                        {
                          "title": "사전 검증이 성공하였습니다.",
                          "text": "↑ PR LINK",
                          "title_link": "${{ github.event.repository.html_url }}/pull/${{ github.event.number }}",
                          "color": "good",
                          "author_name": "${{ github.actor }}",
                          "author_icon": "${{ github.event.sender.avatar_url }}"
                        }
                      ]
            - name: Slack Notification on Failure
              if: ${{ failure() }}
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                  text: '*<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|MySpot API Pre-Check Failure::${{ env.GITHUB_REF_SLUG }}>*'
                  attachments: |
                      [
                        {
                          "title": "사전 검증에 실패하였습니다.",
                          "text": "↑ PR LINK",
                          "title_link": "${{ github.event.repository.html_url }}/pull/${{ github.event.number }}",
                          "color": "danger",
                          "author_name": "${{ github.actor }}",
                          "author_icon": "${{ github.event.sender.avatar_url }}"
                        }
                      ]
